apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: todo-app
  labels:
    app: todo-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: todo-backend

  template:
    metadata:
      labels:
        app: todo-backend

    spec:
      containers:
        - name: backend

          # CHANGE THIS to your Docker Hub username
          image: harshith00000/todo-backend:8

          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:
            - name: SERVER_PORT
              value: "8080"

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://todo-mysql:3306/todo_db?createDatabaseIfNotExist=true"

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: MYSQL_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: MYSQL_PASSWORD

            - name: COHERE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: COHERE_API_KEY

            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: SLACK_WEBHOOK_URL

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
