apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-mysql
  namespace: todo-app
  labels:
    app: todo-mysql

spec:
  replicas: 1

  selector:
    matchLabels:
      app: todo-mysql

  template:
    metadata:
      labels:
        app: todo-mysql

    spec:
      containers:
        - name: mysql
          image: mysql:8.0

          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: MYSQL_DATABASE

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: MYSQL_USERNAME

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: MYSQL_PASSWORD

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -u root -p"$MYSQL_ROOT_PASSWORD"

            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -u root -p"$MYSQL_ROOT_PASSWORD"

            initialDelaySeconds: 30
            periodSeconds: 20
