# Stage 1: Build
FROM maven:3.9.9-eclipse-temurin-17 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests


# Stage 2: Runtime
FROM eclipse-temurin:17-jre

WORKDIR /app

RUN useradd -r -u 1001 springuser

COPY --from=build /app/target/todo-summary-assistant-0.0.1-SNAPSHOT.jar app.jar

RUN chown springuser:springuser app.jar

USER springuser

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
